### ISSUE TITLE
inosca slides

### ISSUE THREAD

**Issue by czosel** [digital-sustainability/cas-pst#9]
Hi @MarkusTiede 

Ich habe die Slides für morgen noch etwas angepasst und ergänzt: https://github.com/digital-sustainability/cas-pst/blob/24/docs/module/3/1/inosca.pdf

Falls du noch spontanes Feedback hast, gerne! :-)

Lieber Gruss, Christian

**Comment by MarkusTiede** [comment]
Ganz lieben Dank @czosel !
